export const TODO = {
  TODO_DELETE: "TODO_DELETE",
  TODO_EDIT: "TODO_EDIT",
  TODO_ADD: "TODO_ADD",
  TODO_DONE: "TODO_DONE",
  TODO_LOADING: "TODO_LOADING",
  TODO_ERROR: "TODO_ERROR",
  TODO_FILTER: "TODO_FILTER",
  TODO_FETCH_COMPLETE: "TODO_FETCH_COMPLETE",
  // TODO_FILTER: "TODO_FILTER", // selector!
};
export const USER = {
  USER_REGISTER: "USER_REGISTER",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_ERROR: "USER_ERROR"
};